### PR TITLE
add support for specifying project

### LINKED ISSUE #77: ability to specify where to run
useful for monorepos

### PR DESCRIPTION
**Pull request by chrisdrackett**
closes #77

### CODE REVIEW

**Comment by geoperez** [comment]
I would love this feature!

**Comment by iCrawl** [comment]
@chrisdrackett this has a lot of opinionated style changes? Any reason why?

**Comment by chrisdrackett** [comment]
these are defaults from prettier, sorry, I'm not used to working on projects that don't have a prettier config so I didn't even notice these until you said something! I can look into removing them after the holidays when I have time

**Comment by iCrawl** [comment]
It wasn't my intention to snatch this away, but I made some structural changes overall and made changes according to how the new GitHub actions are working, while also implementing this in 20c7522db1d8bcb31d3a3e1454c3d7d7ba06e3ef

**Comment by geoperez** [comment]
Is the new version ready to use? I set the project argument, but it didn't work.

**Comment by iCrawl** [comment]
It should be, how did you set it?

**Comment by geoperez** [comment]
I have this:

```
      - name: tsc
        uses: icrawl/action-tsc@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          project: 'src/Unosquare.AssetCore.Server/client-app/tsconfig.json'
```

My output:

```
Added matchers: 'tsc'. Problem matchers scan action output for known warning or error strings and report these inline.
/usr/local/bin/node /home/runner/work/assetcore/assetcore/node_modules/typescript/bin/tsc --noEmit --noErrorTruncation --pretty false
internal/modules/cjs/loader.js:800
    throw err;
    ^
```

There is an error because it's trying to get the `tsc` binary from the root. I can address this later, but I don't see the `--project` flag.

**Comment by geoperez** [comment]
My bad, I didn't realize I need to use `with` instead of `env`. Let me try it!

**Pull request closed without merging**
